"use client";

import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/provider/Providers";
import SideBar from "@/components/SideBar";
import Header from "@/components/Header";
import { usePathname, useRouter } from "next/navigation";
import { useEffect } from "react";


// export const metadata: Metadata = {
//     title: "Management Site",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const pathname = usePathname();
    const router = useRouter();
    const isLogginPage = pathname === '/login';

    // Using router to redirect, DONT use redirect since it's from the server side
    useEffect(() => {
        const isLoggedIn = localStorage.getItem('userInfo');
        if (!isLogginPage && !isLoggedIn) {
            router.push('/login');
        }
    }, [pathname, isLogginPage, router]);

    return (
        <html lang="en">
            <body>
                <Providers>
                    {!isLogginPage ? (
                        <div className="flex flex-row bg-gray-50">

                            {/* Left section: Sidebar */}
                            <div className="w-1/6 bg-white shadow-md border-r-1 z-50">
                                <SideBar />
                            </div>

                            {/* Right section: Header & Main Content */}
                            <div className="w-5/6 flex flex-col ">
                                <Header />
                                <div className="p-10 min-h-screen">
                                    {children}
                                </div>
                            </div>

                        </div>
                    ) :
                        <div>
                            {children}
                        </div>
                    }
                </Providers>
            </body>
        </html>
    );
}
